const products = [
  {
    id: 1,
    name: "Laptop",
    price: 1500,
    image: "Images/Laptop.jpg",
    description: "A high-performance laptop for all your computing needs.",
    category: "Electronics",
    stock: 10,
    rating: 4.5,
    reviews: 120,
  },
  {
    id: 2,
    name: "Phone",
    price: 999,
    image: "Images/Phone.jpg",
    description: "A smartphone with a stunning display and powerful processor.",
    category: "Electronics",
    stock: 25,
    rating: 4.7,
    reviews: 320,
  },
  {
    id: 3,
    name: "Headphones",
    price: 199,
    image: "Images/Headphones.jpg",
    description: "Wireless headphones with noise cancellation and rich sound.",
    category: "Accessories",
    stock: 50,
    rating: 4.3,
    reviews: 85,
  },
  {
    id: 4,
    name: "Smartwatch",
    price: 149,
    image: "Images/smartwatch.jpg",
    description: "A smartwatch with fitness tracking and notification support.",
    category: "Wearable",
    stock: 30,
    rating: 4.0,
    reviews: 45,
  },
  {
    id: 5,
    name: "Tablet",
    price: 499,
    image: "Images/Tablet.jpg",
    description:
      "A lightweight tablet with a crisp display and long battery life.",
    category: "Electronics",
    stock: 20,
    rating: 4.2,
    reviews: 210,
  },
  {
    id: 6,
    name: "Camera",
    price: 850,
    image: "Images/Camera.jpg",
    description: "Capture stunning photos and videos with this DSLR camera.",
    category: "Photography",
    stock: 15,
    rating: 4.6,
    reviews: 150,
  },
];

export default products;
